
import { Language } from './types';

export const TRANSLATIONS: Record<Language, any> = {
  en: {
    home: 'Home',
    profile: 'Profile',
    admin: 'Admin',
    search: 'Search movies...',
    trending: 'Trending',
    genres: 'Genres',
    favorites: 'Favorites',
    premiere: 'Premiere / New',
    logout: 'Logout',
    addMovie: 'Add Movie',
    edit: 'Edit',
    delete: 'Delete',
    save: 'Save',
    title: 'Title',
    description: 'Description',
    genre: 'Genre',
    language: 'Language',
    subtitles: 'Subtitles',
    uploadCover: 'Upload Cover',
    uploadVideo: 'Upload Video',
    settings: 'Settings',
    changeLanguage: 'Change Language',
    login: 'Login',
    register: 'Register',
    email: 'Email',
    password: 'Password',
    errorAccount: 'Account not found',
    errorPassword: 'Wrong password',
    play: 'Play',
    watchMovie: 'Watch Movie',
    rateMovie: 'Rate Movie',
    releaseDate: 'Release Date',
    producers: 'Producers',
    directors: 'Directors',
    manageAdmins: 'Manage Admins',
    addAdmin: 'Add Admin',
    ownerCode: 'Owner Code',
    permissions: 'Permissions',
    permPublish: 'Publish Movies',
    permEdit: 'Edit Movies',
    permDelete: 'Delete Movies',
    invalidCode: 'Invalid Owner Code',
    adminAdded: 'Admin added successfully',
    onlyOwner: 'Only owner can manage admins',
    aiAssistant: 'Sakura AI',
    aiPlaceholder: 'Ask the Spirit of Motion...',
    aiGenMetadata: 'AI Generate'
  },
  ru: {
    home: 'Главная',
    profile: 'Профиль',
    admin: 'Админ',
    search: 'Поиск...',
    trending: 'В тренде',
    genres: 'Жанры',
    favorites: 'Избранное',
    premiere: 'Премьера / Новое',
    logout: 'Выйти',
    addMovie: 'Добавить фильм',
    edit: 'Редактировать',
    delete: 'Удалить',
    save: 'Сохранить',
    title: 'Название',
    description: 'Описание',
    genre: 'Жанр',
    language: 'Язык',
    subtitles: 'Субтитры',
    uploadCover: 'Загрузить обложку',
    uploadVideo: 'Загрузить видео',
    settings: 'Настройки',
    changeLanguage: 'Сменить язык',
    login: 'Войти',
    register: 'Регистрация',
    email: 'Почта',
    password: 'Пароль',
    errorAccount: 'Аккаунт не найден',
    errorPassword: 'Пароль неверный',
    play: 'Смотреть',
    watchMovie: 'Смотреть фильм',
    rateMovie: 'Оценить фильм',
    releaseDate: 'Дата выхода',
    producers: 'Продюсеры',
    directors: 'Режиссёры',
    manageAdmins: 'Управление админами',
    addAdmin: 'Добавить админа',
    ownerCode: 'Код владельца',
    permissions: 'Права доступа',
    permPublish: 'Публикация',
    permEdit: 'Редактирование',
    permDelete: 'Удаление',
    invalidCode: 'Неверный код владельца',
    adminAdded: 'Админ добавлен',
    onlyOwner: 'Только владелец может управлять админами',
    aiAssistant: 'Дух Сакуры',
    aiPlaceholder: 'Спроси у Духа Кино...',
    aiGenMetadata: 'ИИ Генерация'
  },
  ua: {
    home: 'Головна',
    profile: 'Профіль',
    admin: 'Адмін',
    search: 'Пошук...',
    trending: 'У тренді',
    genres: 'Жанри',
    favorites: 'Обране',
    premiere: 'Прем\'єра / Нове',
    logout: 'Вийти',
    addMovie: 'Додати фільм',
    edit: 'Редагувати',
    delete: 'Видалити',
    save: 'Зберегти',
    title: 'Назва',
    description: 'Опис',
    genre: 'Жанр',
    language: 'Мова',
    subtitles: 'Субтитри',
    uploadCover: 'Завантажити обкладинку',
    uploadVideo: 'Завантажити відео',
    settings: 'Налаштування',
    changeLanguage: 'Змінити мову',
    login: 'Увійти',
    register: 'Реєстрація',
    email: 'Електронна пошта',
    password: 'Пароль',
    errorAccount: 'Акаунт не знайдено',
    errorPassword: 'Пароль невірний',
    play: 'Дивитись',
    watchMovie: 'Дивитись фільм',
    rateMovie: 'Оцінити фільм',
    releaseDate: 'Дата виходу',
    producers: 'Продюсери',
    directors: 'Режисери',
    manageAdmins: 'Керування адмінами',
    addAdmin: 'Додати адміна',
    ownerCode: 'Код власника',
    permissions: 'Дозволи',
    permPublish: 'Публікація',
    permEdit: 'Редагування',
    permDelete: 'Видалення',
    invalidCode: 'Невірний код власника',
    adminAdded: 'Адмін доданий',
    onlyOwner: 'Тільки власник може керувати адмінами',
    aiAssistant: 'Дух Сакури',
    aiPlaceholder: 'Запитай у Духа Кіно...',
    aiGenMetadata: 'ІІ Генерація'
  },
  be: {
    home: 'Галоўная',
    profile: 'Профіль',
    admin: 'Адмін',
    search: 'Пошук...',
    trending: 'У трэндзе',
    genres: 'Жанры',
    favorites: 'Выбранае',
    premiere: 'Прэм\'ера / Новае',
    logout: 'Выйсці',
    addMovie: 'Дадаць фільм',
    edit: 'Рэдагаваць',
    delete: 'Выдаліць',
    save: 'Захаваць',
    title: 'Назва',
    description: 'Апісанне',
    genre: 'Жанр',
    language: 'Мова',
    subtitles: 'Субтытры',
    uploadCover: 'Загрузіць вокладку',
    uploadVideo: 'Загрузіць відэа',
    settings: 'Налады',
    changeLanguage: 'Змяніць мову',
    login: 'Увайсці',
    register: 'Рэгістрацыя',
    email: 'Электронная пошта',
    password: 'Пароль',
    errorAccount: 'Акаўнт не знойдзены',
    errorPassword: 'Пароль няправільны',
    play: 'Глядзець',
    watchMovie: 'Глядзець фільм',
    rateMovie: 'Ацаніць фільм',
    releaseDate: 'Дата выхаду',
    producers: 'Прадзюсары',
    directors: 'Рэжысёры',
    manageAdmins: 'Кіраванне адмінамі',
    addAdmin: 'Дадаць адміна',
    ownerCode: 'Код уладальніка',
    permissions: 'Правы доступу',
    permPublish: 'Публікацыя',
    permEdit: 'Рэдагаванне',
    permDelete: 'Выдаленне',
    invalidCode: 'Няправільны код уладальніка',
    adminAdded: 'Адмін дададзены',
    onlyOwner: 'Толькі ўладальнік можа кіраваць адмінамі',
    aiAssistant: 'Дух Сакуры',
    aiPlaceholder: 'Спытай у Духа Кіно...',
    aiGenMetadata: 'ІІ Генерацыя'
  },
  kk: {
    home: 'Басты бет',
    profile: 'Профиль',
    admin: 'Админ',
    search: 'Іздеу...',
    trending: 'Трендте',
    genres: 'Жанрлар',
    favorites: 'Таңдаулылар',
    premiere: 'Премьера / Жаңа',
    logout: 'Шығу',
    addMovie: 'Фильм қосу',
    edit: 'Өңдеу',
    delete: 'Жою',
    save: 'Сақтау',
    title: 'Атауы',
    description: 'Сипаттамасы',
    genre: 'Жанр',
    language: 'Тіл',
    subtitles: 'Субтитрлер',
    uploadCover: 'Мұқабаны жүктеу',
    uploadVideo: 'Бейнені жүктеу',
    settings: 'Параметрлер',
    changeLanguage: 'Тілді өзгерту',
    login: 'Кіру',
    register: 'Тіркелу',
    email: 'Электрондық пошта',
    password: 'Құпия сөз',
    errorAccount: 'Аккаунт табылмады',
    errorPassword: 'Құпия сөз қате',
    play: 'Көру',
    watchMovie: 'Фильмді көру',
    rateMovie: 'Фильмді бағалау',
    releaseDate: 'Шыққан күні',
    producers: 'Продюсерлер',
    directors: 'Режиссерлер',
    manageAdmins: 'Админдерді басқару',
    addAdmin: 'Админ қосу',
    ownerCode: 'Иесінің коды',
    permissions: 'Рұқсаттар',
    permPublish: 'Жариялау',
    permEdit: 'Өңдеу',
    permDelete: 'Жою',
    invalidCode: 'Иесінің коды қате',
    adminAdded: 'Админ қосылды',
    onlyOwner: 'Тек иесі админдерді басқара алады',
    aiAssistant: 'Сакура Рухы',
    aiPlaceholder: 'Кино Рухынан сұра...',
    aiGenMetadata: 'ЖИ Генерация'
  }
};

export const INITIAL_MOVIES: any[] = [
  {
    id: '1',
    title: 'Starry Void',
    description: 'A deep journey into the unknown parts of our galaxy, exploring nebulaes and forgotten solar systems.',
    genre: 'Sci-Fi',
    language: 'English',
    subtitles: ['English', 'Russian'],
    coverUrl: 'https://picsum.photos/seed/space/400/600',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    releaseDate: '2024-12-15',
    producers: ['Alan Sokal', 'Marie Curie'],
    directors: ['Christopher Nolan'],
    isTrending: true,
    isNew: true
  },
  {
    id: '2',
    title: 'Cyber Runner',
    description: 'In the year 2099, Neo-Tokyo is a city of rain, neon lights, and forgotten souls looking for redemption.',
    genre: 'Fantasy',
    language: 'Japanese',
    subtitles: ['English', 'Kazakh'],
    coverUrl: 'https://picsum.photos/seed/cyber/400/600',
    videoUrl: 'https://www.w3schools.com/html/movie.mp4',
    releaseDate: '2025-01-02',
    producers: ['Hideo Kojima'],
    directors: ['Mamoru Oshii'],
    isTrending: true
  },
  {
    id: '3',
    title: 'Laugh Out Loud',
    description: 'A collection of the most hilarious, unexpected, and heartwarming moments from across the globe.',
    genre: 'Comedy',
    language: 'Russian',
    subtitles: ['Belarusian'],
    coverUrl: 'https://picsum.photos/seed/comedy/400/600',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    releaseDate: '2023-05-10',
    producers: ['Seth Rogen', 'Evan Goldberg'],
    directors: ['Taika Waititi'],
    isNew: true
  }
];
